# LiveKit SFU configuration for Nexus
# Domain: lche2.xvps.jp

port: 7880
rtc:
  # UDP port for WebRTC media
  port_range_start: 7882
  port_range_end: 7882
  # Use TCP fallback if UDP is blocked
  tcp_port: 7881
  # Announce the public IP so ICE candidates are correct
  node_ip: 162.43.31.143
  use_external_ip: false

# TLS — use Let's Encrypt cert
turn:
  enabled: false
  # TURN ports (5349/3478) are not open on VPS firewall.
  # Disabled to prevent ICE agent from wasting time on unreachable TURN candidates.

# API keys — used by lk-jwt-service to sign tokens
keys:
  nexus-api: 0930254ce08f85941dd721f2eea601d1941d2353810367fdd94f758c78b5fd11

# Logging — keep minimal to avoid disk bloat
logging:
  level: warn
  json: false

# Room settings
room:
  auto_create: true
  empty_timeout: 300    # 5 min: close room when empty
  max_participants: 12
