# LiveKit SFU configuration for Nexus
# Domain: lche2.xvps.jp

port: 7880
rtc:
  # UDP port for WebRTC media
  port_range_start: 7882
  port_range_end: 7882
  # Use TCP fallback if UDP is blocked
  tcp_port: 7881
  # Announce the public IP so ICE candidates are correct
  node_ip: 162.43.31.143
  use_external_ip: false
  # 帯域に応じた自動品質調整
  congestion_control:
    enabled: true
    allow_pause: true
  # キーフレーム間隔を短縮（デフォルト約4s → 2s）
  # キーフレーム損失時の復帰が早くなる（ビットレート微増）
  pli_throttle:
    low_quality: 500ms
    mid_quality: 800ms
    high_quality: 1s

# Opus RED: パケットロス時に直前パケットのコピーで補完（音声途切れ大幅改善）
audio:
  active_red_encoding: true

# TLS — use Let's Encrypt cert
turn:
  enabled: false
  # TURN ports (5349/3478) are not open on VPS firewall.
  # Disabled to prevent ICE agent from wasting time on unreachable TURN candidates.

# API keys — used by lk-jwt-service to sign tokens
keys:
  nexus-api: 0930254ce08f85941dd721f2eea601d1941d2353810367fdd94f758c78b5fd11

# Logging — keep minimal to avoid disk bloat
logging:
  level: warn
  json: false

# Room settings
room:
  auto_create: true
  empty_timeout: 300    # 5 min: close room when empty
  max_participants: 12
  # 不要なコーデックを除外して SDP サイズ削減 → ネゴシエーション高速化
  enabled_codecs:
    - mime: audio/opus
    - mime: audio/red
    - mime: video/vp8
    - mime: video/h264
